# Generated by Django 4.2.4 on 2024-01-20 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_parcel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parcel',
        ),
    ]
