# Generated by Django 4.2.4 on 2024-01-20 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parcel',
        ),
    ]
