# Generated by Django 4.2.4 on 2024-01-20 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
        ('Admin', '0002_delete_parcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('parcel_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_address', models.TextField()),
                ('sender_phone', models.CharField(max_length=15)),
                ('from_branch', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_address', models.TextField()),
                ('recipient_contact', models.CharField(max_length=15)),
                ('to_branch', models.CharField(max_length=255)),
                ('parcel_description', models.TextField()),
                ('parcel_weight', models.FloatField()),
                ('shipping_service', models.CharField(max_length=255)),
                ('fragile', models.BooleanField(default=False)),
                ('parcel_status', models.CharField(max_length=255)),
                ('safe_product', models.BooleanField(default=False)),
                ('staff_assigned_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Staff.staff')),
            ],
        ),
    ]
