# Generated by Django 4.2.4 on 2024-01-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_parcel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='fragile',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='safe_product',
        ),
        migrations.AddField(
            model_name='parcel',
            name='sensitive_content',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
